name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Update this to the exact version that you want to test i.e. the packaging
  # into a Docker image.
  VERSION: 1.3.1

jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
      IMAGE: zappi/k8s-ttl-controller
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: TwiN/k8s-ttl-controller
          ref: v${{ env.VERSION }}
      - name: Prepare Image Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Test Multi-Arch Building Of Image
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          annotations: ${{ steps.metadata.outputs.annotations }}
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
